spring:
  application:
    name: notecloud

  datasource:
    url: jdbc:postgresql://localhost:5432/notecloud
    username: postgres
    password: "Joanna$2006"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080